sd::path::prepend "$HOME/usr/bin"
sd::path::prepend "$HOME/usr/bin"
sd::path::prepend "$HOME/.yarn/bin"
sd::path::prepend "$HOME/.config/yarn/global/node_modules/.bin"
sd::path::prepend "$HOME/.cargo/bin"
